/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PatientsPetIdRouteImport } from './routes/patients.$petId'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as PetsIndexRouteImport } from './routes/pets.index'
import { Route as PetsPetIdRouteImport } from './routes/pets.$petId'
import { Route as PetsNewRouteImport } from './routes/pets.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPetIdRoute = PatientsPetIdRouteImport.update({
  id: '/patients/$petId',
  path: '/patients/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/community': typeof CommunityRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/patients': typeof PatientsRoute
  '/patients/$petId': typeof PatientsPetIdRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/pets/': typeof PetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/community': typeof CommunityRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/patients': typeof PatientsRoute
  '/patients/$petId': typeof PatientsPetIdRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/pets': typeof PetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/community': typeof CommunityRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/patients': typeof PatientsRoute
  '/patients/$petId': typeof PatientsPetIdRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/pets/': typeof PetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/community'
    | '/discover'
    | '/home'
    | '/impact'
    | '/patients'
    | '/patients/$petId'
    | '/modules'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/verify'
    | '/welcome'
    | '/community/$postId'
    | '/pets/$petId'
    | '/pets/new'
    | '/pets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/community'
    | '/discover'
    | '/home'
    | '/impact'
    | '/patients'
    | '/patients/$petId'
    | '/modules'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/verify'
    | '/welcome'
    | '/community/$postId'
    | '/pets/$petId'
    | '/pets/new'
    | '/pets'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/community'
    | '/discover'
    | '/home'
    | '/impact'
    | '/patients'
    | '/patients/$petId'
    | '/modules'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/verify'
    | '/welcome'
    | '/community/$postId'
    | '/pets/$petId'
    | '/pets/new'
    | '/pets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  HomeRoute: typeof HomeRoute
  ImpactRoute: typeof ImpactRoute
  PatientsRoute: typeof PatientsRoute
  PatientsPetIdRoute: typeof PatientsPetIdRoute
  ModulesRoute: typeof ModulesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  PetsPetIdRoute: typeof PetsPetIdRoute
  PetsNewRoute: typeof PetsNewRoute
  PetsIndexRoute: typeof PetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$petId': {
      id: '/patients/$petId'
      path: '/patients/$petId'
      fullPath: '/patients/$petId'
      preLoaderRoute: typeof PatientsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets/'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  CommunityRoute: CommunityRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  HomeRoute: HomeRoute,
  ImpactRoute: ImpactRoute,
  PatientsRoute: PatientsRoute,
  PatientsPetIdRoute: PatientsPetIdRoute,
  ModulesRoute: ModulesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  PetsPetIdRoute: PetsPetIdRoute,
  PetsNewRoute: PetsNewRoute,
  PetsIndexRoute: PetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
