/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as CityRouteImport } from './routes/city'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as CouncilLoginRouteImport } from './routes/council-login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DvsRouteImport } from './routes/dvs'
import { Route as DvsLoginRouteImport } from './routes/dvs-login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LicenceReturnRouteImport } from './routes/licence-return'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VetRouteImport } from './routes/vet'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as CallCallIdRouteImport } from './routes/call.$callId'
import { Route as CertificateCodeRouteImport } from './routes/certificate.$code'
import { Route as ChatsConversationIdRouteImport } from './routes/chats_.$conversationId'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as CommunityClipsRouteImport } from './routes/community.clips'
import { Route as PatientsPetIdRouteImport } from './routes/patients.$petId'
import { Route as PetsIndexRouteImport } from './routes/pets.index'
import { Route as PetsPetIdRouteImport } from './routes/pets.$petId'
import { Route as PetsNewRouteImport } from './routes/pets.new'
import { Route as ApiPaynowInitiateRouteImport } from './routes/api.paynow.initiate'
import { Route as ApiPaynowPollRouteImport } from './routes/api.paynow.poll'
import { Route as ApiPaynowResultRouteImport } from './routes/api.paynow.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilLoginRoute = CouncilLoginRouteImport.update({
  id: '/council-login',
  path: '/council-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DvsRoute = DvsRouteImport.update({
  id: '/dvs',
  path: '/dvs',
  getParentRoute: () => rootRouteImport,
} as any)
const DvsLoginRoute = DvsLoginRouteImport.update({
  id: '/dvs-login',
  path: '/dvs-login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenceReturnRoute = LicenceReturnRouteImport.update({
  id: '/licence-return',
  path: '/licence-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VetRoute = VetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCallIdRoute = CallCallIdRouteImport.update({
  id: '/call/$callId',
  path: '/call/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCodeRoute = CertificateCodeRouteImport.update({
  id: '/certificate/$code',
  path: '/certificate/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsConversationIdRoute = ChatsConversationIdRouteImport.update({
  id: '/chats_/$conversationId',
  path: '/chats/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityClipsRoute = CommunityClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => CommunityRoute,
} as any)
const PatientsPetIdRoute = PatientsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => PatientsRoute,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/pets/$petId',
  path: '/pets/$petId',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaynowInitiateRoute = ApiPaynowInitiateRouteImport.update({
  id: '/api/paynow/initiate',
  path: '/api/paynow/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaynowPollRoute = ApiPaynowPollRouteImport.update({
  id: '/api/paynow/poll',
  path: '/api/paynow/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaynowResultRoute = ApiPaynowResultRouteImport.update({
  id: '/api/paynow/result',
  path: '/api/paynow/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/chats': typeof ChatsRoute
  '/city': typeof CityRoute
  '/community': typeof CommunityRouteWithChildren
  '/council': typeof CouncilRoute
  '/council-login': typeof CouncilLoginRoute
  '/discover': typeof DiscoverRoute
  '/dvs': typeof DvsRoute
  '/dvs-login': typeof DvsLoginRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/licence-return': typeof LicenceReturnRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/vet': typeof VetRoute
  '/welcome': typeof WelcomeRoute
  '/call/$callId': typeof CallCallIdRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/clips': typeof CommunityClipsRoute
  '/patients/$petId': typeof PatientsPetIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/pets/': typeof PetsIndexRoute
  '/api/paynow/initiate': typeof ApiPaynowInitiateRoute
  '/api/paynow/poll': typeof ApiPaynowPollRoute
  '/api/paynow/result': typeof ApiPaynowResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/chats': typeof ChatsRoute
  '/city': typeof CityRoute
  '/community': typeof CommunityRouteWithChildren
  '/council': typeof CouncilRoute
  '/council-login': typeof CouncilLoginRoute
  '/discover': typeof DiscoverRoute
  '/dvs': typeof DvsRoute
  '/dvs-login': typeof DvsLoginRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/licence-return': typeof LicenceReturnRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/vet': typeof VetRoute
  '/welcome': typeof WelcomeRoute
  '/call/$callId': typeof CallCallIdRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/clips': typeof CommunityClipsRoute
  '/patients/$petId': typeof PatientsPetIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/pets': typeof PetsIndexRoute
  '/api/paynow/initiate': typeof ApiPaynowInitiateRoute
  '/api/paynow/poll': typeof ApiPaynowPollRoute
  '/api/paynow/result': typeof ApiPaynowResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/chats': typeof ChatsRoute
  '/city': typeof CityRoute
  '/community': typeof CommunityRouteWithChildren
  '/council': typeof CouncilRoute
  '/council-login': typeof CouncilLoginRoute
  '/discover': typeof DiscoverRoute
  '/dvs': typeof DvsRoute
  '/dvs-login': typeof DvsLoginRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/licence-return': typeof LicenceReturnRoute
  '/modules': typeof ModulesRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/presentation': typeof PresentationRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/vet': typeof VetRoute
  '/welcome': typeof WelcomeRoute
  '/call/$callId': typeof CallCallIdRoute
  '/certificate/$code': typeof CertificateCodeRoute
  '/chats_/$conversationId': typeof ChatsConversationIdRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/community/clips': typeof CommunityClipsRoute
  '/patients/$petId': typeof PatientsPetIdRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/new': typeof PetsNewRoute
  '/pets/': typeof PetsIndexRoute
  '/api/paynow/initiate': typeof ApiPaynowInitiateRoute
  '/api/paynow/poll': typeof ApiPaynowPollRoute
  '/api/paynow/result': typeof ApiPaynowResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/chats'
    | '/city'
    | '/community'
    | '/council'
    | '/council-login'
    | '/discover'
    | '/dvs'
    | '/dvs-login'
    | '/home'
    | '/impact'
    | '/licence-return'
    | '/modules'
    | '/notifications'
    | '/patients'
    | '/presentation'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/verify'
    | '/vet'
    | '/welcome'
    | '/call/$callId'
    | '/certificate/$code'
    | '/chats/$conversationId'
    | '/community/$postId'
    | '/community/clips'
    | '/patients/$petId'
    | '/pets/$petId'
    | '/pets/new'
    | '/pets/'
    | '/api/paynow/initiate'
    | '/api/paynow/poll'
    | '/api/paynow/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/chats'
    | '/city'
    | '/community'
    | '/council'
    | '/council-login'
    | '/discover'
    | '/dvs'
    | '/dvs-login'
    | '/home'
    | '/impact'
    | '/licence-return'
    | '/modules'
    | '/notifications'
    | '/patients'
    | '/presentation'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/verify'
    | '/vet'
    | '/welcome'
    | '/call/$callId'
    | '/certificate/$code'
    | '/chats/$conversationId'
    | '/community/$postId'
    | '/community/clips'
    | '/patients/$petId'
    | '/pets/$petId'
    | '/pets/new'
    | '/pets'
    | '/api/paynow/initiate'
    | '/api/paynow/poll'
    | '/api/paynow/result'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/chats'
    | '/city'
    | '/community'
    | '/council'
    | '/council-login'
    | '/discover'
    | '/dvs'
    | '/dvs-login'
    | '/home'
    | '/impact'
    | '/licence-return'
    | '/modules'
    | '/notifications'
    | '/patients'
    | '/presentation'
    | '/profile'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/verify'
    | '/vet'
    | '/welcome'
    | '/call/$callId'
    | '/certificate/$code'
    | '/chats_/$conversationId'
    | '/community/$postId'
    | '/community/clips'
    | '/patients/$petId'
    | '/pets/$petId'
    | '/pets/new'
    | '/pets/'
    | '/api/paynow/initiate'
    | '/api/paynow/poll'
    | '/api/paynow/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ChatsRoute: typeof ChatsRoute
  CityRoute: typeof CityRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  CouncilRoute: typeof CouncilRoute
  CouncilLoginRoute: typeof CouncilLoginRoute
  DiscoverRoute: typeof DiscoverRoute
  DvsRoute: typeof DvsRoute
  DvsLoginRoute: typeof DvsLoginRoute
  HomeRoute: typeof HomeRoute
  ImpactRoute: typeof ImpactRoute
  LicenceReturnRoute: typeof LicenceReturnRoute
  ModulesRoute: typeof ModulesRoute
  NotificationsRoute: typeof NotificationsRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PresentationRoute: typeof PresentationRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  VetRoute: typeof VetRoute
  WelcomeRoute: typeof WelcomeRoute
  CallCallIdRoute: typeof CallCallIdRoute
  CertificateCodeRoute: typeof CertificateCodeRoute
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
  PetsPetIdRoute: typeof PetsPetIdRoute
  PetsNewRoute: typeof PetsNewRoute
  PetsIndexRoute: typeof PetsIndexRoute
  ApiPaynowInitiateRoute: typeof ApiPaynowInitiateRoute
  ApiPaynowPollRoute: typeof ApiPaynowPollRoute
  ApiPaynowResultRoute: typeof ApiPaynowResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council-login': {
      id: '/council-login'
      path: '/council-login'
      fullPath: '/council-login'
      preLoaderRoute: typeof CouncilLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dvs': {
      id: '/dvs'
      path: '/dvs'
      fullPath: '/dvs'
      preLoaderRoute: typeof DvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dvs-login': {
      id: '/dvs-login'
      path: '/dvs-login'
      fullPath: '/dvs-login'
      preLoaderRoute: typeof DvsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licence-return': {
      id: '/licence-return'
      path: '/licence-return'
      fullPath: '/licence-return'
      preLoaderRoute: typeof LicenceReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet': {
      id: '/vet'
      path: '/vet'
      fullPath: '/vet'
      preLoaderRoute: typeof VetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$callId': {
      id: '/call/$callId'
      path: '/call/$callId'
      fullPath: '/call/$callId'
      preLoaderRoute: typeof CallCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$code': {
      id: '/certificate/$code'
      path: '/certificate/$code'
      fullPath: '/certificate/$code'
      preLoaderRoute: typeof CertificateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats_/$conversationId': {
      id: '/chats_/$conversationId'
      path: '/chats/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/clips': {
      id: '/community/clips'
      path: '/clips'
      fullPath: '/community/clips'
      preLoaderRoute: typeof CommunityClipsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/patients/$petId': {
      id: '/patients/$petId'
      path: '/$petId'
      fullPath: '/patients/$petId'
      preLoaderRoute: typeof PatientsPetIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets/'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paynow/initiate': {
      id: '/api/paynow/initiate'
      path: '/api/paynow/initiate'
      fullPath: '/api/paynow/initiate'
      preLoaderRoute: typeof ApiPaynowInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paynow/poll': {
      id: '/api/paynow/poll'
      path: '/api/paynow/poll'
      fullPath: '/api/paynow/poll'
      preLoaderRoute: typeof ApiPaynowPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paynow/result': {
      id: '/api/paynow/result'
      path: '/api/paynow/result'
      fullPath: '/api/paynow/result'
      preLoaderRoute: typeof ApiPaynowResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  CommunityClipsRoute: typeof CommunityClipsRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
  CommunityClipsRoute: CommunityClipsRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface PatientsRouteChildren {
  PatientsPetIdRoute: typeof PatientsPetIdRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPetIdRoute: PatientsPetIdRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ChatsRoute: ChatsRoute,
  CityRoute: CityRoute,
  CommunityRoute: CommunityRouteWithChildren,
  CouncilRoute: CouncilRoute,
  CouncilLoginRoute: CouncilLoginRoute,
  DiscoverRoute: DiscoverRoute,
  DvsRoute: DvsRoute,
  DvsLoginRoute: DvsLoginRoute,
  HomeRoute: HomeRoute,
  ImpactRoute: ImpactRoute,
  LicenceReturnRoute: LicenceReturnRoute,
  ModulesRoute: ModulesRoute,
  NotificationsRoute: NotificationsRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PresentationRoute: PresentationRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  VetRoute: VetRoute,
  WelcomeRoute: WelcomeRoute,
  CallCallIdRoute: CallCallIdRoute,
  CertificateCodeRoute: CertificateCodeRoute,
  ChatsConversationIdRoute: ChatsConversationIdRoute,
  PetsPetIdRoute: PetsPetIdRoute,
  PetsNewRoute: PetsNewRoute,
  PetsIndexRoute: PetsIndexRoute,
  ApiPaynowInitiateRoute: ApiPaynowInitiateRoute,
  ApiPaynowPollRoute: ApiPaynowPollRoute,
  ApiPaynowResultRoute: ApiPaynowResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
